name: g_core
description: "A new Flutter package project."
version: 0.0.1
homepage: 'https://github.com/g-kit/g_core'
repository: 'https://github.com/g-kit/g_core'
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  g_lib:
    path: ../g_lib
  
  g_common:
    path: ../g_common
  
  g_model:
    path: ../g_model

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
