name: g_lib
description: "A new Flutter package project."
version: 0.0.1
homepage: ''
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 유틸성 라이브러리
  path_provider: ^2.1.5          # 파일 경로 관련
  app_links: ^6.4.0              # 앱 링크 관련

  # 인증 라이브러리
  local_auth: ^2.3.0             # 생체 인식 관련

  # 권한 라이브러리
  permission_handler: ^12.0.1     # 권한 관리

  # 공유 기능 라이브러리
  share_plus: ^11.0.0            # 공유 기능 관련

  # 스토리지 라이브러리
  sqflite: ^2.4.2               # 로컬 db 데이터베이스
  flutter_secure_storage: ^9.2.4 # 보안 스토리지
  shared_preferences: ^2.5.3     # 공유 환경 변수

  # 네트워크 라이브러리
  dio: ^5.8.0+1                 # 네트워크 라이브러리
  socket_io_client: ^3.1.2      # 소켓 라이브러리
  http_certificate_pinning: ^3.0.1 # 인증서 파이닝 관련

  # 라우팅 라이브러리
  go_router: ^16.0.0             # 라우팅 라이브러리


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
